### ISSUE TITLE
Problem statement

### ISSUE THREAD

**Issue by akshaybahadur21** [jovianjaison/CBIR#1]
Hi, @jovianjaison @prakhar308 ,

This repository looks great.
I want you guys to display the problem statement with this repository.
This is going to help the users understand what exactly you are trying to solve in the first place.
You can add your comments in the readme file itself.

You can find reference here -> https://github.com/huggingface/transformers

PS : You guys should ask questions.

**Comment by jovianjaison** [comment]
Added the problem statement with features and possible applications.
Please review this pull request:
#2

We still are yet to finalize the UI elements and deployment environment.We're still working with different algorithms for getting good results .Will update the installation steps, demo and other portions in README eventually.

**Comment by akshaybahadur21** [comment]
Looks good now.
@jovianjaison
