### ISSUE TITLE
Getting the data

### ISSUE THREAD

**Issue by akshaybahadur21** [jovianjaison/CBIR#3]
Great work guys.
@prakhar308 @jovianjaison @pranjalichaudhari 
So now let's move onto some coding aspect.
What I would like you guys to do is follow a prototype-approach where we can implement small features quickly so that we can have a small workable demo at the end of every week or 2 weeks.

    Step 1 : Getting the dataset.

You can create dataset, scrape from internet, use a preexisting dataset.
I want you guys to explain me why did you use this dataset only?

PS - **You can ask me questions in this thread.**

**Comment by pranjalichaudhari** [comment]
The CIFAR-10 dataset - 
Reason : 
It has huge number of images that belong to different categories. The dataset has 60k colour images in 10 classes, 6000 images per class. There are 50k training images and 10k test images. **The classes are completely mutually exclusive**. The image resolution is 32 × 32 which allows us to try different algorithms quickly.
Link :  http://www.cs.toronto.edu/~kriz/cifar.html

**Comment by jovianjaison** [comment]
We are currently using the Wang1k dataset.However, the major issue is the class assigned to each image, for example there were 2 classes tribal people and beaches, most of the beach images had people in them thus there was decrease in accuracy in classifying them, both content and label vise.
I think assigning multiple classes to images and using multi class classification would give better accuracy as well as help create a more general and practical model.

I found this vast and interesting dataset called Open Images Dataset v5.It has ~9Million images, with multiple labels.It also has object location annotations which could be useful later.
https://storage.googleapis.com/openimages/web/download.html

The original dataset is 18Tb, we could use the 'Object detection track' '2018-19 challenge' test set which has around 60,00,000 images with 500 classes and annotation data.
https://storage.googleapis.com/openimages/web/challenge2019.html

**Comment by akshaybahadur21** [comment]
@jovianjaison @pranjalichaudhari - makes sense.
However, one thing to notice is that for training on 18tb of data, you need to have lot of resources.
Anyway, for starters, I need you guys to pick up any dataset which you want to work on.
Remember, high accuracy doesn't matter, your approach ad understanding is more important.
Let me know which dataset you want to go ahead with.

**Comment by pranjalichaudhari** [comment]
We have decided to go ahead with the CIFAR-10 dataset.

**Comment by akshaybahadur21** [comment]
@pranjalichaudhari @jovianjaison @prakhar308  - Makes sense.
Keep an eye on the issues section.
