### ISSUE TITLE
Visualization and Understanding the data

### ISSUE THREAD

**Issue by akshaybahadur21** [jovianjaison/CBIR#4]
Now that we have the dataset ready, we need to visualize and understand it.
This is important because,

- Help us understand the requirement of more data
- Whether the classes are imbalance

How should this be done,

- A good starting point will be [Dipanjan's repo](https://github.com/dipanjanS/art_of_data_visualization)
- You should explore more over the internet.

The end goal is to make even a normal person realize the patterns in data and that could be achieved effective visualization.

**Comment by akshaybahadur21** [comment]
@prakhar308 @jovianjaison @pranjalichaudhari @RohanAwhad  - any updates?

**Comment by RohanAwhad** [comment]
@akshaybahadur21 
We are still researching on different methods for unstructured data visualisation. The repo you shared with us had some techniques but we are unable to figure out what things to infer from that visualization.

**Comment by akshaybahadur21** [comment]
@RohanAwhad - Basically, you dont have to come up with a lengthy explanation,  some simple techniques will be good. We just want to get some sort of a visual representation of data.
Also, Google is always a good place to find a good starting point not just this repo.

**Comment by akshaybahadur21** [comment]
@RohanAwhad - Any updates?
